name = "agentlink-backend"
main = "dist/index.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

[env.development]
name = "agentlink-backend-dev"

[vars]
BASE_URL = "https://agentlink-backend.agentlink.workers.dev"
MANAGER_AGENT_URL = "https://agentlink-backend.agentlink.workers.dev/manager"
REGISTRY_URL = "https://agentlink-backend.agentlink.workers.dev/registry"