name = "agentlink-backend"
main = "dist/index.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

[env.development]
name = "agentlink-backend-dev"

[vars]
MANAGER_AGENT_URL = "http://localhost:8787/manager"
REGISTRY_URL = "http://localhost:8787/registry"